--Top Customers by Balance
SELECT c.full_name, a.balance
FROM customers c
JOIN accounts a ON c.customer_id = a.customer_id
ORDER BY a.balance DESC;

--Total Transactions per Account
SELECT account_id, COUNT(*) as total_transactions
FROM transactions
GROUP BY account_id;

select * from transactions;

--Monthly Summary
SELECT TO_CHAR(transaction_date,'MM-YYYY') AS month, SUM(amount)
FROM transactions
GROUP BY TO_CHAR(transaction_date,'MM-YYYY');

--Customer Loan Details
SELECT c.full_name, l.loan_type, l.loan_amount
FROM customers c
JOIN loans l ON c.customer_id = l.customer_id;

--Customers without Loans
SELECT full_name
FROM customers
WHERE customer_id NOT IN (SELECT customer_id FROM loans);

-- ACCOUNT DATA
INSERT INTO accounts (account_id, customer_id, branch_id, account_number, account_type, balance, currency, status, opened_date, last_updated) VALUES (17, 17, 1, '252530', 'SAVINGS', 853357.48, 'INR', 'ACTIVE', TO_DATE('11/04/2019', 'MM/DD/YYYY'), TO_DATE('11/09/2001', 'MM/DD/YYYY'));
INSERT INTO accounts (account_id, customer_id, branch_id, account_number, account_type, balance, currency, status, opened_date, last_updated) VALUES (18, 18, 1, '922314', 'SAVINGS', 49016.14, 'INR', 'ACTIVE', TO_DATE('11/08/2004', 'MM/DD/YYYY'), TO_DATE('06/04/2006', 'MM/DD/YYYY'));
INSERT INTO accounts (account_id, customer_id, branch_id, account_number, account_type, balance, currency, status, opened_date, last_updated) VALUES (19, 19, 1, '884598', 'SAVINGS', 650098.82, 'EUR', 'ACTIVE', TO_DATE('06/23/2005', 'MM/DD/YYYY'), TO_DATE('04/13/2011', 'MM/DD/YYYY'));
INSERT INTO accounts (account_id, customer_id, branch_id, account_number, account_type, balance, currency, status, opened_date, last_updated) VALUES (20, 20, 1, '578514', 'CURRENT', 645224.97, 'USD', 'DORMANT', TO_DATE('03/19/2019', 'MM/DD/YYYY'), TO_DATE('09/07/2016', 'MM/DD/YYYY'));
INSERT INTO accounts (account_id, customer_id, branch_id, account_number, account_type, balance, currency, status, opened_date, last_updated) VALUES (21, 21, 1, '136341', 'CURRENT', 585666.31, 'EUR', 'ACTIVE', TO_DATE('10/09/2003', 'MM/DD/YYYY'), TO_DATE('03/18/2003', 'MM/DD/YYYY'));
INSERT INTO accounts (account_id, customer_id, branch_id, account_number, account_type, balance, currency, status, opened_date, last_updated) VALUES (22, 22, 1, '571907', 'SAVINGS', 521698.39, 'USD', 'CLOSED', TO_DATE('11/26/2020', 'MM/DD/YYYY'), TO_DATE('07/31/2013', 'MM/DD/YYYY'));
INSERT INTO accounts (account_id, customer_id, branch_id, account_number, account_type, balance, currency, status, opened_date, last_updated) VALUES (23, 23, 1, '442661', 'CURRENT', 3589.46, 'EUR', 'ACTIVE', TO_DATE('04/03/2007', 'MM/DD/YYYY'), TO_DATE('10/25/2010', 'MM/DD/YYYY'));
INSERT INTO accounts (account_id, customer_id, branch_id, account_number, account_type, balance, currency, status, opened_date, last_updated) VALUES (24, 24, 1, '285711', 'CURRENT', 244162.97, 'EUR', 'ACTIVE', TO_DATE('10/17/2013', 'MM/DD/YYYY'), TO_DATE('05/31/2008', 'MM/DD/YYYY'));
INSERT INTO accounts (account_id, customer_id, branch_id, account_number, account_type, balance, currency, status, opened_date, last_updated) VALUES (25, 25, 1, '512160', 'SAVINGS', 821585.96, 'USD', 'CLOSED', TO_DATE('11/21/2018', 'MM/DD/YYYY'), TO_DATE('05/15/2008', 'MM/DD/YYYY'));
INSERT INTO accounts (account_id, customer_id, branch_id, account_number, account_type, balance, currency, status, opened_date, last_updated) VALUES (26, 26, 1, '879772', 'CURRENT', 935186.96, 'USD', 'ACTIVE', TO_DATE('06/15/2004', 'MM/DD/YYYY'), TO_DATE('02/02/2000', 'MM/DD/YYYY'));
INSERT INTO accounts (account_id, customer_id, branch_id, account_number, account_type, balance, currency, status, opened_date, last_updated) VALUES (27, 27, 1, '250681', 'CURRENT', 890410.11, 'INR', 'ACTIVE', TO_DATE('05/13/2016', 'MM/DD/YYYY'), TO_DATE('05/29/2014', 'MM/DD/YYYY'));
INSERT INTO accounts (account_id, customer_id, branch_id, account_number, account_type, balance, currency, status, opened_date, last_updated) VALUES (28, 28, 1, '803002', 'CURRENT', 949961.49, 'EUR', 'DORMANT', TO_DATE('12/20/2001', 'MM/DD/YYYY'), TO_DATE('09/13/2007', 'MM/DD/YYYY'));
INSERT INTO accounts (account_id, customer_id, branch_id, account_number, account_type, balance, currency, status, opened_date, last_updated) VALUES (29, 29, 1, '630215', 'CURRENT', 675859.96, 'USD', 'CLOSED', TO_DATE('9/18/2011', 'MM/DD/YYYY'), TO_DATE('06/02/2004', 'MM/DD/YYYY'));
INSERT INTO accounts (account_id, customer_id, branch_id, account_number, account_type, balance, currency, status, opened_date, last_updated) VALUES (30, 30, 1, '873540', 'SAVINGS', 875839.41, 'INR', 'ACTIVE', TO_DATE('04/17/2016', 'MM/DD/YYYY'), TO_DATE('03/05/2011', 'MM/DD/YYYY'));
INSERT INTO accounts (account_id, customer_id, branch_id, account_number, account_type, balance, currency, status, opened_date, last_updated) VALUES (31, 31, 1, '635802', 'SAVINGS', 615283.61, 'USD', 'DORMANT', TO_DATE('12/3/2016', 'MM/DD/YYYY'), TO_DATE('02/24/2005', 'MM/DD/YYYY'));
INSERT INTO accounts (account_id, customer_id, branch_id, account_number, account_type, balance, currency, status, opened_date, last_updated) VALUES (32, 32, 1, '331336', 'SAVINGS', 871629.22, 'INR', 'ACTIVE', TO_DATE('09/14/2004', 'MM/DD/YYYY'), TO_DATE('12/09/2007', 'MM/DD/YYYY'));
INSERT INTO accounts (account_id, customer_id, branch_id, account_number, account_type, balance, currency, status, opened_date, last_updated) VALUES (33, 33, 1, '782323', 'CURRENT', 711426.7, 'INR', 'DORMANT', TO_DATE('10/28/2007', 'MM/DD/YYYY'), TO_DATE('07/05/2022', 'MM/DD/YYYY'));
INSERT INTO accounts (account_id, customer_id, branch_id, account_number, account_type, balance, currency, status, opened_date, last_updated) VALUES (34, 34, 1, '732382', 'CURRENT', 584462.42, 'USD', 'ACTIVE', TO_DATE('05/15/2011', 'MM/DD/YYYY'), TO_DATE('01/01/2011', 'MM/DD/YYYY'));


-- Corrected Transactions Data for Oracle
-- Harry, ensure you have inserted account_ids 1-75 before running this.

INSERT INTO transactions (transaction_id, account_id, transaction_type, amount, transaction_mode, transaction_date, remarks) VALUES (1, 1, 'DEPOSIT', 258263.18, 'ONLINE', TO_DATE('11/19/2022', 'MM/DD/YYYY'), 'nunc nisl duis bibendum felis sed interdum venenatis turpis enim blandit mi');
INSERT INTO transactions (transaction_id, account_id, transaction_type, amount, transaction_mode, transaction_date, remarks) VALUES (2, 2, 'WITHDRAWAL', 626886.25, 'ATM', TO_DATE('12/08/2021', 'MM/DD/YYYY'), 'natoque penatibus et magnis dis parturient montes nascetur ridiculus mus vivamus');
INSERT INTO transactions (transaction_id, account_id, transaction_type, amount, transaction_mode, transaction_date, remarks) VALUES (3, 3, 'TRANSFER', 829886.55, 'UPI', TO_DATE('12/12/2022', 'MM/DD/YYYY'), 'in tempus sit amet sem fusce consequat nulla nisl nunc nisl duis bibendum felis sed interdum');
INSERT INTO transactions (transaction_id, account_id, transaction_type, amount, transaction_mode, transaction_date, remarks) VALUES (4, 4, 'DEPOSIT', 494554.83, 'CASH', TO_DATE('08/08/2022', 'MM/DD/YYYY'), 'nisl venenatis lacinia aenean sit amet justo morbi ut odio cras mi pede malesuada in imperdiet');
INSERT INTO transactions (transaction_id, account_id, transaction_type, amount, transaction_mode, transaction_date, remarks) VALUES (5, 5, 'WITHDRAWAL', 200462.85, 'ATM', TO_DATE('02/24/2022', 'MM/DD/YYYY'), 'sapien non mi integer ac neque duis bibendum morbi non quam nec dui luctus rutrum');
INSERT INTO transactions (transaction_id, account_id, transaction_type, amount, transaction_mode, transaction_date, remarks) VALUES (6, 6, 'TRANSFER', 458536.19, 'ONLINE', TO_DATE('06/01/2022', 'MM/DD/YYYY'), 'dapibus dolor vel est donec odio justo sollicitudin ut suscipit a feugiat et eros vestibulum ac est');
INSERT INTO transactions (transaction_id, account_id, transaction_type, amount, transaction_mode, transaction_date, remarks) VALUES (7, 7, 'DEPOSIT', 765802.85, 'CASH', TO_DATE('10/02/2022', 'MM/DD/YYYY'), 'aliquet massa id lobortis convallis tortor risus dapibus augue vel accumsan tellus nisi eu orci mauris lacinia sapien quis libero');
INSERT INTO transactions (transaction_id, account_id, transaction_type, amount, transaction_mode, transaction_date, remarks) VALUES (8, 8, 'WITHDRAWAL', 373900.01, 'ATM', TO_DATE('08/31/2022', 'MM/DD/YYYY'), 'montes nascetur ridiculus mus vivamus vestibulum sagittis sapien cum sociis natoque penatibus et magnis dis parturient montes');
INSERT INTO transactions (transaction_id, account_id, transaction_type, amount, transaction_mode, transaction_date, remarks) VALUES (9, 9, 'TRANSFER', 677070.9, 'UPI', TO_DATE('11/08/2020', 'MM/DD/YYYY'), 'in blandit ultrices enim lorem ipsum dolor sit amet consectetuer adipiscing elit proin interdum mauris');
INSERT INTO transactions (transaction_id, account_id, transaction_type, amount, transaction_mode, transaction_date, remarks) VALUES (10, 10, 'DEPOSIT', 69049.14, 'ONLINE', TO_DATE('09/17/2020', 'MM/DD/YYYY'), 'laoreet ut rhoncus aliquet pulvinar sed nisl nunc rhoncus dui vel sem sed sagittis nam congue risus semper porta');
INSERT INTO transactions (transaction_id, account_id, transaction_type, amount, transaction_mode, transaction_date, remarks) VALUES (11, 11, 'WITHDRAWAL', 272029.58, 'ATM', TO_DATE('02/19/2020', 'MM/DD/YYYY'), 'orci vehicula condimentum curabitur in libero ut massa volutpat convallis morbi');
INSERT INTO transactions (transaction_id, account_id, transaction_type, amount, transaction_mode, transaction_date, remarks) VALUES (12, 12, 'TRANSFER', 230625.6, 'UPI', TO_DATE('12/24/2021', 'MM/DD/YYYY'), 'orci luctus et ultrices posuere cubilia curae nulla dapibus dolor vel est donec odio justo sollicitudin');
INSERT INTO transactions (transaction_id, account_id, transaction_type, amount, transaction_mode, transaction_date, remarks) VALUES (13, 13, 'DEPOSIT', 939710.02, 'CASH', TO_DATE('11/16/2020', 'MM/DD/YYYY'), 'vestibulum ante ipsum primis in faucibus orci luctus et ultrices');
INSERT INTO transactions (transaction_id, account_id, transaction_type, amount, transaction_mode, transaction_date, remarks) VALUES (14, 14, 'WITHDRAWAL', 777370.54, 'ONLINE', TO_DATE('11/05/2020', 'MM/DD/YYYY'), 'duis consequat dui nec nisi volutpat eleifend donec ut dolor morbi vel lectus in');
INSERT INTO transactions (transaction_id, account_id, transaction_type, amount, transaction_mode, transaction_date, remarks) VALUES (15, 15, 'TRANSFER', 885357.84, 'UPI', TO_DATE('09/25/2021', 'MM/DD/YYYY'), 'aenean sit amet justo morbi ut odio cras mi pede malesuada in');
INSERT INTO transactions (transaction_id, account_id, transaction_type, amount, transaction_mode, transaction_date, remarks) VALUES (16, 16, 'DEPOSIT', 84160.8, 'CASH', TO_DATE('07/24/2022', 'MM/DD/YYYY'), 'vehicula condimentum curabitur in libero ut massa volutpat convallis morbi odio odio elementum eu interdum eu');
INSERT INTO transactions (transaction_id, account_id, transaction_type, amount, transaction_mode, transaction_date, remarks) VALUES (17, 17, 'WITHDRAWAL', 94499.06, 'ATM', TO_DATE('06/04/2022', 'MM/DD/YYYY'), 'et commodo vulputate justo in blandit ultrices enim lorem ipsum dolor sit amet');
INSERT INTO transactions (transaction_id, account_id, transaction_type, amount, transaction_mode, transaction_date, remarks) VALUES (18, 18, 'TRANSFER', 360435.04, 'ONLINE', TO_DATE('08/26/2021', 'MM/DD/YYYY'), 'faucibus cursus urna ut tellus nulla ut erat id mauris vulputate elementum nullam varius nulla facilisi cras non');
INSERT INTO transactions (transaction_id, account_id, transaction_type, amount, transaction_mode, transaction_date, remarks) VALUES (19, 19, 'DEPOSIT', 592598.5, 'CASH', TO_DATE('11/27/2022', 'MM/DD/YYYY'), 'justo eu massa donec dapibus duis at velit eu est congue elementum in hac habitasse platea dictumst morbi');
INSERT INTO transactions (transaction_id, account_id, transaction_type, amount, transaction_mode, transaction_date, remarks) VALUES (20, 20, 'WITHDRAWAL', 5690.51, 'ATM', TO_DATE('08/22/2020', 'MM/DD/YYYY'), 'consequat dui nec nisi volutpat eleifend donec ut dolor morbi vel lectus in quam fringilla rhoncus');
INSERT INTO transactions (transaction_id, account_id, transaction_type, amount, transaction_mode, transaction_date, remarks) VALUES (21, 21, 'TRANSFER', 998248.6, 'UPI', TO_DATE('07/18/2020', 'MM/DD/YYYY'), 'at lorem integer tincidunt ante vel ipsum praesent blandit lacinia erat vestibulum');
INSERT INTO transactions (transaction_id, account_id, transaction_type, amount, transaction_mode, transaction_date, remarks) VALUES (22, 22, 'DEPOSIT', 406541.49, 'ONLINE', TO_DATE('01/19/2022', 'MM/DD/YYYY'), 'eu felis fusce posuere felis sed lacus morbi sem mauris laoreet ut rhoncus aliquar pulvinar sed nisl nunc');
INSERT INTO transactions (transaction_id, account_id, transaction_type, amount, transaction_mode, transaction_date, remarks) VALUES (23, 23, 'WITHDRAWAL', 190336.43, 'ATM', TO_DATE('03/27/2021', 'MM/DD/YYYY'), 'non ligula pellentesque ultrices phasellus id sapien in sapien iaculis congue vivamus metus arcu adipiscing molestie');
INSERT INTO transactions (transaction_id, account_id, transaction_type, amount, transaction_mode, transaction_date, remarks) VALUES (24, 24, 'TRANSFER', 679765.94, 'UPI', TO_DATE('01/07/2021', 'MM/DD/YYYY'), 'est phasellus sit amet erat nulla tempus vivamus in felis eu sapien cursus vestibulum proin eu mi nulla ac');
INSERT INTO transactions (transaction_id, account_id, transaction_type, amount, transaction_mode, transaction_date, remarks) VALUES (25, 25, 'DEPOSIT', 826404.18, 'CASH', TO_DATE('01/22/2021', 'MM/DD/YYYY'), 'nibh in hac habitasse platea dictumst aliquam augue quam sollicitudin vitae consectetuer eget rutrum at');
INSERT INTO transactions (transaction_id, account_id, transaction_type, amount, transaction_mode, transaction_date, remarks) VALUES (26, 26, 'WITHDRAWAL', 977353.89, 'ATM', TO_DATE('12/31/2021', 'MM/DD/YYYY'), 'eu est congue elementum in hac habitasse platea dictumst morbi vestibulum velit id pretium');
INSERT INTO transactions (transaction_id, account_id, transaction_type, amount, transaction_mode, transaction_date, remarks) VALUES (27, 27, 'TRANSFER', 342360.18, 'ONLINE', TO_DATE('04/13/2021', 'MM/DD/YYYY'), 'hendrerit at vulputate vitae nisl aenean lectus pellentesque eget nunc donec quis orci eget orci vehicula condimentum');
INSERT INTO transactions (transaction_id, account_id, transaction_type, amount, transaction_mode, transaction_date, remarks) VALUES (28, 28, 'DEPOSIT', 399302.23, 'CASH', TO_DATE('04/29/2020', 'MM/DD/YYYY'), 'leo maecenas pulvinar lobortis est phasellus sit amet erat nulla tempus vivamus in felis eu sapien cursus vestibulum proin');
INSERT INTO transactions (transaction_id, account_id, transaction_type, amount, transaction_mode, transaction_date, remarks) VALUES (29, 29, 'WITHDRAWAL', 59818.2, 'ATM', TO_DATE('07/26/2021', 'MM/DD/YYYY'), 'nec sem duis aliquam convallis nunc proin at turpis a pede posuere nonummy');
INSERT INTO transactions (transaction_id, account_id, transaction_type, amount, transaction_mode, transaction_date, remarks) VALUES (30, 30, 'TRANSFER', 619885.36, 'UPI', TO_DATE('05/06/2022', 'MM/DD/YYYY'), 'at nulla suspendisse potenti cras in purus eu magna vulputate luctus cum sociis natoque penatibus et magnis dis parturient montes');
INSERT INTO transactions (transaction_id, account_id, transaction_type, amount, transaction_mode, transaction_date, remarks) VALUES (31, 31, 'DEPOSIT', 525121.49, 'ONLINE', TO_DATE('09/08/2021', 'MM/DD/YYYY'), 'pede justo lacinia eget tincidunt eget tempus vel pede morbi');
INSERT INTO transactions (transaction_id, account_id, transaction_type, amount, transaction_mode, transaction_date, remarks) VALUES (32, 32, 'WITHDRAWAL', 5525.34, 'ATM', TO_DATE('08/15/2022', 'MM/DD/YYYY'), 'dui nec nisi volutpat eleifend donec ut dolor morbi vel lectus in quam');
INSERT INTO transactions (transaction_id, account_id, transaction_type, amount, transaction_mode, transaction_date, remarks) VALUES (33, 33, 'TRANSFER', 36879.24, 'UPI', TO_DATE('07/24/2021', 'MM/DD/YYYY'), 'vestibulum proin eu mi nulla ac enim in tempor turpis nec euismod');
INSERT INTO transactions (transaction_id, account_id, transaction_type, amount, transaction_mode, transaction_date, remarks) VALUES (34, 34, 'DEPOSIT', 751396.74, 'CASH', TO_DATE('04/30/2021', 'MM/DD/YYYY'), 'diam erat fermentum justo nec condimentum neque sapien placerat ante nulla justo');
INSERT INTO transactions (transaction_id, account_id, transaction_type, amount, transaction_mode, transaction_date, remarks) VALUES (35, 35, 'WITHDRAWAL', 150695.54, 'ATM', TO_DATE('02/27/2020', 'MM/DD/YYYY'), 'ac est lacinia nisi venenatis tristique fusce congue diam id ornare imperdiet sapien urna pretium nisl');
INSERT INTO transactions (transaction_id, account_id, transaction_type, amount, transaction_mode, transaction_date, remarks) VALUES (36, 36, 'TRANSFER', 538272.42, 'ONLINE', TO_DATE('05/11/2020', 'MM/DD/YYYY'), 'dolor vel est donec odio justo sollicitudin ut suscipit a feugiat et eros');
INSERT INTO transactions (transaction_id, account_id, transaction_type, amount, transaction_mode, transaction_date, remarks) VALUES (37, 37, 'DEPOSIT', 951408.35, 'CASH', TO_DATE('09/23/2021', 'MM/DD/YYYY'), 'tellus in sagittis dui vel nisl duis ac nibh fusce lacus purus aliquet at feugiat non pretium');
INSERT INTO transactions (transaction_id, account_id, transaction_type, amount, transaction_mode, transaction_date, remarks) VALUES (38, 38, 'WITHDRAWAL', 67218.58, 'ATM', TO_DATE('10/20/2020', 'MM/DD/YYYY'), 'eget tempus vel pede morbi porttitor lorem id ligula suspendisse ornare consequat lectus');
INSERT INTO transactions (transaction_id, account_id, transaction_type, amount, transaction_mode, transaction_date, remarks) VALUES (39, 39, 'TRANSFER', 346251.52, 'UPI', TO_DATE('06/05/2022', 'MM/DD/YYYY'), 'diam erat fermentum justo nec condimentum neque sapien placerat ante nulla justo');
INSERT INTO transactions (transaction_id, account_id, transaction_type, amount, transaction_mode, transaction_date, remarks) VALUES (40, 40, 'DEPOSIT', 245504.75, 'ONLINE', TO_DATE('11/21/2021', 'MM/DD/YYYY'), 'in imperdiet et commodo vulputate justo in blandit ultrices enim lorem ipsum dolor sit');
INSERT INTO transactions (transaction_id, account_id, transaction_type, amount, transaction_mode, transaction_date, remarks) VALUES (41, 41, 'WITHDRAWAL', 723459.63, 'ATM', TO_DATE('01/09/2021', 'MM/DD/YYYY'), 'id justo sit amet sapien dignissim vestibulum vestibulum ante ipsum primis in faucibus orci luctus et');
INSERT INTO transactions (transaction_id, account_id, transaction_type, amount, transaction_mode, transaction_date, remarks) VALUES (42, 42, 'TRANSFER', 290028.41, 'UPI', TO_DATE('02/16/2022', 'MM/DD/YYYY'), 'luctus et ultrices posuere cubilia curae donec pharetra magna vestibulum aliquet');
INSERT INTO transactions (transaction_id, account_id, transaction_type, amount, transaction_mode, transaction_date, remarks) VALUES (43, 43, 'DEPOSIT', 770670.43, 'CASH', TO_DATE('08/29/2020', 'MM/DD/YYYY'), 'lobortis convallis tortor risus dapibus augue vel accumsan tellus nisi eu orci mauris lacinia sapien quis libero nullam sit amet');
INSERT INTO transactions (transaction_id, account_id, transaction_type, amount, transaction_mode, transaction_date, remarks) VALUES (44, 44, 'WITHDRAWAL', 527068.13, 'ONLINE', TO_DATE('03/26/2021', 'MM/DD/YYYY'), 'donec posuere metus vitae ipsum aliquam non mauris morbi non lectus aliquam sit amet diam in magna bibendum imperdiet nullam');
INSERT INTO transactions (transaction_id, account_id, transaction_type, amount, transaction_mode, transaction_date, remarks) VALUES (45, 45, 'TRANSFER', 57472.7, 'UPI', TO_DATE('10/13/2020', 'MM/DD/YYYY'), 'at vulputate vitae nisl aenean lectus pellentesque eget nunc donec quis orci');
INSERT INTO transactions (transaction_id, account_id, transaction_type, amount, transaction_mode, transaction_date, remarks) VALUES (46, 46, 'DEPOSIT', 300648.29, 'CASH', TO_DATE('11/24/2022', 'MM/DD/YYYY'), 'aliquam lacus morbi quis tortor id nulla ultrices aliquet maecenas leo odio condimentum id luctus nec molestie sed');
INSERT INTO transactions (transaction_id, account_id, transaction_type, amount, transaction_mode, transaction_date, remarks) VALUES (47, 47, 'WITHDRAWAL', 397858.2, 'ATM', TO_DATE('07/14/2020', 'MM/DD/YYYY'), 'lacinia sapien quis libero nullam sit amet turpis elementum ligula vehicula consequat morbi');
INSERT INTO transactions (transaction_id, account_id, transaction_type, amount, transaction_mode, transaction_date, remarks) VALUES (48, 48, 'TRANSFER', 412756.1, 'ONLINE', TO_DATE('08/27/2022', 'MM/DD/YYYY'), 'lacinia aenean sit amet justo morbi ut odio cras mi pede malesuada in imperdiet et commodo vulputate justo in blandit');
INSERT INTO transactions (transaction_id, account_id, transaction_type, amount, transaction_mode, transaction_date, remarks) VALUES (49, 49, 'DEPOSIT', 411841.16, 'CASH', TO_DATE('10/20/2020', 'MM/DD/YYYY'), 'maecenas tincidunt lacus at velit vivamus vel nulla eget eros elementum pellentesque quisque porta');
INSERT INTO transactions (transaction_id, account_id, transaction_type, amount, transaction_mode, transaction_date, remarks) VALUES (50, 50, 'WITHDRAWAL', 339998.82, 'ATM', TO_DATE('04/08/2020', 'MM/DD/YYYY'), 'rutrum at lorem integer tincidunt ante vel ipsum praesent blandit lacinia erat');
INSERT INTO transactions (transaction_id, account_id, transaction_type, amount, transaction_mode, transaction_date, remarks) VALUES (51, 51, 'TRANSFER', 49890.55, 'UPI', TO_DATE('10/08/2021', 'MM/DD/YYYY'), 'dolor sit amet consectetuer adipiscing elit proin risus praesent lectus vestibulum quam');
INSERT INTO transactions (transaction_id, account_id, transaction_type, amount, transaction_mode, transaction_date, remarks) VALUES (52, 52, 'DEPOSIT', 816248.63, 'ONLINE', TO_DATE('12/09/2021', 'MM/DD/YYYY'), 'est phasellus sit amet erat nulla tempus vivamus in felis');
INSERT INTO transactions (transaction_id, account_id, transaction_type, amount, transaction_mode, transaction_date, remarks) VALUES (53, 53, 'WITHDRAWAL', 896151.47, 'ATM', TO_DATE('11/07/2022', 'MM/DD/YYYY'), 'sapien in sapien iaculis congue vivamus metus arcu adipiscing molestie hendrerit at vulputate vitae nisl aenean lectus pellentesque eget nunc');
INSERT INTO transactions (transaction_id, account_id, transaction_type, amount, transaction_mode, transaction_date, remarks) VALUES (54, 54, 'TRANSFER', 279718.56, 'UPI', TO_DATE('01/04/2021', 'MM/DD/YYYY'), 'at feugiat non pretium quis lectus suspendisse potenti in eleifend quam a');
INSERT INTO transactions (transaction_id, account_id, transaction_type, amount, transaction_mode, transaction_date, remarks) VALUES (55, 55, 'DEPOSIT', 1127.57, 'CASH', TO_DATE('07/30/2022', 'MM/DD/YYYY'), 'dolor quis odio consequat varius integer ac leo pellentesque ultrices mattis odio donec');
INSERT INTO transactions (transaction_id, account_id, transaction_type, amount, transaction_mode, transaction_date, remarks) VALUES (56, 56, 'WITHDRAWAL', 25564.38, 'ATM', TO_DATE('11/18/2022', 'MM/DD/YYYY'), 'lobortis convallis tortor risus dapibus augue vel accumsan tellus nisi eu orci mauris lacinia sapien quis libero');
INSERT INTO transactions (transaction_id, account_id, transaction_type, amount, transaction_mode, transaction_date, remarks) VALUES (57, 57, 'TRANSFER', 661607.24, 'ONLINE', TO_DATE('09/19/2021', 'MM/DD/YYYY'), 'erat nulla tempus vivamus in felis eu sapien cursus vestibulum proin eu mi nulla ac');
INSERT INTO transactions (transaction_id, account_id, transaction_type, amount, transaction_mode, transaction_date, remarks) VALUES (58, 58, 'DEPOSIT', 903771.13, 'CASH', TO_DATE('03/18/2020', 'MM/DD/YYYY'), 'gravida sem praesent id massa id nisl venenatis lacinia aenean sit amet justo');
INSERT INTO transactions (transaction_id, account_id, transaction_type, amount, transaction_mode, transaction_date, remarks) VALUES (59, 59, 'WITHDRAWAL', 710882.84, 'ATM', TO_DATE('11/04/2020', 'MM/DD/YYYY'), 'id sapien in sapien iaculis congue vivamus metus arcu adipiscing molestie hendrerit at vulputate');
INSERT INTO transactions (transaction_id, account_id, transaction_type, amount, transaction_mode, transaction_date, remarks) VALUES (60, 60, 'TRANSFER', 693812.85, 'UPI', TO_DATE('01/23/2021', 'MM/DD/YYYY'), 'hac habitasse platea dictumst morbi vestibulum velit id pretium iaculis diam erat fermentum justo nec condimentum neque');
INSERT INTO transactions (transaction_id, account_id, transaction_type, amount, transaction_mode, transaction_date, remarks) VALUES (61, 61, 'DEPOSIT', 943123.05, 'ONLINE', TO_DATE('09/09/2021', 'MM/DD/YYYY'), 'varius nulla facilisi cras non velit nec nisi vulputate nonummy maecenas tincidunt');
INSERT INTO transactions (transaction_id, account_id, transaction_type, amount, transaction_mode, transaction_date, remarks) VALUES (62, 62, 'WITHDRAWAL', 199945.71, 'ATM', TO_DATE('07/02/2020', 'MM/DD/YYYY'), 'id lobortis convallis tortor risus dapibus augue vel accumsan tellus nisi eu orci mauris lacinia sapien quis');
INSERT INTO transactions (transaction_id, account_id, transaction_type, amount, transaction_mode, transaction_date, remarks) VALUES (63, 63, 'TRANSFER', 136486.8, 'UPI', TO_DATE('12/08/2020', 'MM/DD/YYYY'), 'nisl venenatis lacinia aenean sit amet justo morbi ut odio cras mi');
INSERT INTO transactions (transaction_id, account_id, transaction_type, amount, transaction_mode, transaction_date, remarks) VALUES (64, 64, 'DEPOSIT', 148715.22, 'CASH', TO_DATE('05/02/2022', 'MM/DD/YYYY'), 'nec nisi vulputate nonummy maecenas tincidunt lacus at velit vivamus vel');
INSERT INTO transactions (transaction_id, account_id, transaction_type, amount, transaction_mode, transaction_date, remarks) VALUES (65, 65, 'WITHDRAWAL', 223468.07, 'ATM', TO_DATE('08/12/2022', 'MM/DD/YYYY'), 'blandit ultrices enim lorem ipsum dolor sit amet consectetuer adipiscing');
INSERT INTO transactions (transaction_id, account_id, transaction_type, amount, transaction_mode, transaction_date, remarks) VALUES (66, 66, 'TRANSFER', 49045.34, 'ONLINE', TO_DATE('01/14/2022', 'MM/DD/YYYY'), 'proin leo odio porttitor id consequat in consequat ut nulla sed accumsan felis');
INSERT INTO transactions (transaction_id, account_id, transaction_type, amount, transaction_mode, transaction_date, remarks) VALUES (67, 67, 'DEPOSIT', 725905.05, 'CASH', TO_DATE('03/02/2021', 'MM/DD/YYYY'), 'sed lacus morbi sem mauris laoreet ut rhoncus aliquet pulvinar sed nisl nunc rhoncus dui vel sem');
INSERT INTO transactions (transaction_id, account_id, transaction_type, amount, transaction_mode, transaction_date, remarks) VALUES (68, 68, 'WITHDRAWAL', 811676.77, 'ATM', TO_DATE('04/20/2022', 'MM/DD/YYYY'), 'ipsum aliquam non mauris morbi non lectus aliquam sit amet');
INSERT INTO transactions (transaction_id, account_id, transaction_type, amount, transaction_mode, transaction_date, remarks) VALUES (69, 69, 'TRANSFER', 726998.81, 'UPI', TO_DATE('04/23/2021', 'MM/DD/YYYY'), 'vestibulum ante ipsum primis in faucibus orci luctus et ultrices');
INSERT INTO transactions (transaction_id, account_id, transaction_type, amount, transaction_mode, transaction_date, remarks) VALUES (70, 70, 'DEPOSIT', 890260.35, 'ONLINE', TO_DATE('09/16/2022', 'MM/DD/YYYY'), 'sapien a libero nam dui proin leo odio porttitor id consequat in consequat ut nulla sed accumsan');
INSERT INTO transactions (transaction_id, account_id, transaction_type, amount, transaction_mode, transaction_date, remarks) VALUES (71, 71, 'WITHDRAWAL', 568973.47, 'ATM', TO_DATE('08/01/2021', 'MM/DD/YYYY'), 'potenti nullam porttitor lacus at turpis donec posuere metus vitae ipsum aliquam non mauris morbi');
INSERT INTO transactions (transaction_id, account_id, transaction_type, amount, transaction_mode, transaction_date, remarks) VALUES (72, 72, 'TRANSFER', 237385.1, 'UPI', TO_DATE('09/21/2020', 'MM/DD/YYYY'), 'praesent blandit nam nulla integer pede justo lacinia eget tincidunt eget tempus vel pede');
INSERT INTO transactions (transaction_id, account_id, transaction_type, amount, transaction_mode, transaction_date, remarks) VALUES (73, 73, 'DEPOSIT', 738295.13, 'CASH', TO_DATE('04/16/2022', 'MM/DD/YYYY'), 'eget nunc donec quis orci eget orci vehicula condimentum curabitur');
INSERT INTO transactions (transaction_id, account_id, transaction_type, amount, transaction_mode, transaction_date, remarks) VALUES (74, 74, 'WITHDRAWAL', 331135.92, 'ATM', TO_DATE('09/09/2020', 'MM/DD/YYYY'), 'massa id nisl venenatis lacinia aenean sit amet justo morbi ut odio cras mi');
INSERT INTO transactions (transaction_id, account_id, transaction_type, amount, transaction_mode, transaction_date, remarks) VALUES (75, 75, 'TRANSFER', 104515.2, 'UPI', TO_DATE('07/18/2020', 'MM/DD/YYYY'), 'consequat dui nec nisi volutpat eleifend donec ut dolor morbi vel lectus');


SELECT * FROM transactions;

INSERT INTO loans (loan_id, customer_id, loan_type, loan_amount, interest_rate, start_date, end_date, status) VALUES (1, 1, 'HOME', 493167.31, 23.22, TO_DATE('7/3/2008', 'MM/DD/YYYY'), NULL, 'DEFAULT');
INSERT INTO loans (loan_id, customer_id, loan_type, loan_amount, interest_rate, start_date, end_date, status) VALUES (2, 2, 'HOME', 84513.77, 11.46, TO_DATE('6/15/2009', 'MM/DD/YYYY'), NULL, 'DEFAULT');
INSERT INTO loans (loan_id, customer_id, loan_type, loan_amount, interest_rate, start_date, end_date, status) VALUES (3, 3, 'AUTO', 657132.67, 9.93, TO_DATE('6/11/2011', 'MM/DD/YYYY'), NULL, 'DEFAULT');
INSERT INTO loans (loan_id, customer_id, loan_type, loan_amount, interest_rate, start_date, end_date, status) VALUES (4, 4, 'AUTO', 495144.63, 3.99, TO_DATE('5/15/2016', 'MM/DD/YYYY'), NULL, 'APPROVED');
INSERT INTO loans (loan_id, customer_id, loan_type, loan_amount, interest_rate, start_date, end_date, status) VALUES (5, 5, 'HOME', 365397.24, 8.05, TO_DATE('10/12/2017', 'MM/DD/YYYY'), NULL, 'PAID');
INSERT INTO loans (loan_id, customer_id, loan_type, loan_amount, interest_rate, start_date, end_date, status) VALUES (6, 6, 'PERSONAL', 772351.85, 2.94, TO_DATE('12/21/2000', 'MM/DD/YYYY'), NULL, 'APPROVED');
INSERT INTO loans (loan_id, customer_id, loan_type, loan_amount, interest_rate, start_date, end_date, status) VALUES (7, 7, 'AUTO', 810094.1, 9.78, TO_DATE('8/20/2012', 'MM/DD/YYYY'), NULL, 'PAID');
INSERT INTO loans (loan_id, customer_id, loan_type, loan_amount, interest_rate, start_date, end_date, status) VALUES (8, 8, 'HOME', 633360.8, 17.69, TO_DATE('1/3/2011', 'MM/DD/YYYY'), NULL, 'APPROVED');
INSERT INTO loans (loan_id, customer_id, loan_type, loan_amount, interest_rate, start_date, end_date, status) VALUES (9, 9, 'HOME', 730936.11, 12.17, TO_DATE('7/1/2020', 'MM/DD/YYYY'), NULL, 'DEFAULT');
INSERT INTO loans (loan_id, customer_id, loan_type, loan_amount, interest_rate, start_date, end_date, status) VALUES (10, 10, 'AUTO', 551768.63, 2.11, TO_DATE('12/4/2002', 'MM/DD/YYYY'), NULL, 'APPROVED');
INSERT INTO loans (loan_id, customer_id, loan_type, loan_amount, interest_rate, start_date, end_date, status) VALUES (11, 11, 'AUTO', 81525.25, 12.06, TO_DATE('8/25/2009', 'MM/DD/YYYY'), NULL, 'APPROVED');
INSERT INTO loans (loan_id, customer_id, loan_type, loan_amount, interest_rate, start_date, end_date, status) VALUES (12, 12, 'PERSONAL', 259162.34, 15.45, TO_DATE('7/26/2000', 'MM/DD/YYYY'), NULL, 'PAID');
INSERT INTO loans (loan_id, customer_id, loan_type, loan_amount, interest_rate, start_date, end_date, status) VALUES (13, 13, 'AUTO', 232245.89, 20.3, TO_DATE('3/17/2006', 'MM/DD/YYYY'), NULL, 'PAID');
INSERT INTO loans (loan_id, customer_id, loan_type, loan_amount, interest_rate, start_date, end_date, status) VALUES (14, 14, 'HOME', 922835.58, 12.3, TO_DATE('1/30/2005', 'MM/DD/YYYY'), NULL, 'PAID');
INSERT INTO loans (loan_id, customer_id, loan_type, loan_amount, interest_rate, start_date, end_date, status) VALUES (15, 15, 'PERSONAL', 945474.75, 14.36, TO_DATE('2/6/2013', 'MM/DD/YYYY'), NULL, 'APPROVED');
INSERT INTO loans (loan_id, customer_id, loan_type, loan_amount, interest_rate, start_date, end_date, status) VALUES (16, 16, 'HOME', 714365.69, 1.63, TO_DATE('2/7/2022', 'MM/DD/YYYY'), NULL, 'PAID');
INSERT INTO loans (loan_id, customer_id, loan_type, loan_amount, interest_rate, start_date, end_date, status) VALUES (17, 17, 'AUTO', 201037.91, 2.5, TO_DATE('6/29/2003', 'MM/DD/YYYY'), NULL, 'PAID');
INSERT INTO loans (loan_id, customer_id, loan_type, loan_amount, interest_rate, start_date, end_date, status) VALUES (18, 18, 'AUTO', 626230.8, 13.44, TO_DATE('6/4/2006', 'MM/DD/YYYY'), NULL, 'PAID');
INSERT INTO loans (loan_id, customer_id, loan_type, loan_amount, interest_rate, start_date, end_date, status) VALUES (19, 19, 'HOME', 871557.33, 12.66, TO_DATE('11/25/2022', 'MM/DD/YYYY'), NULL, 'PAID');
INSERT INTO loans (loan_id, customer_id, loan_type, loan_amount, interest_rate, start_date, end_date, status) VALUES (20, 20, 'AUTO', 288656.25, 23.67, TO_DATE('10/3/2003', 'MM/DD/YYYY'), NULL, 'APPROVED');
INSERT INTO loans (loan_id, customer_id, loan_type, loan_amount, interest_rate, start_date, end_date, status) VALUES (21, 21, 'PERSONAL', 228327.94, 3.03, TO_DATE('6/18/2000', 'MM/DD/YYYY'), NULL, 'PAID');
INSERT INTO loans (loan_id, customer_id, loan_type, loan_amount, interest_rate, start_date, end_date, status) VALUES (22, 22, 'AUTO', 905081.94, 4.64, TO_DATE('4/21/2022', 'MM/DD/YYYY'), NULL, 'APPROVED');
INSERT INTO loans (loan_id, customer_id, loan_type, loan_amount, interest_rate, start_date, end_date, status) VALUES (23, 23, 'PERSONAL', 212820.61, 14.42, TO_DATE('4/29/2020', 'MM/DD/YYYY'), NULL, 'APPROVED');
INSERT INTO loans (loan_id, customer_id, loan_type, loan_amount, interest_rate, start_date, end_date, status) VALUES (24, 24, 'AUTO', 516326.71, 12.66, TO_DATE('9/16/2000', 'MM/DD/YYYY'), NULL, 'DEFAULT');
INSERT INTO loans (loan_id, customer_id, loan_type, loan_amount, interest_rate, start_date, end_date, status) VALUES (25, 25, 'HOME', 455374.38, 6.02, TO_DATE('5/29/2013', 'MM/DD/YYYY'), NULL, 'APPROVED');
INSERT INTO loans (loan_id, customer_id, loan_type, loan_amount, interest_rate, start_date, end_date, status) VALUES (26, 26, 'HOME', 738677.66, 23.95, TO_DATE('7/15/2006', 'MM/DD/YYYY'), NULL, 'DEFAULT');
INSERT INTO loans (loan_id, customer_id, loan_type, loan_amount, interest_rate, start_date, end_date, status) VALUES (27, 27, 'PERSONAL', 301560.53, 16.06, TO_DATE('7/23/2022', 'MM/DD/YYYY'), NULL, 'DEFAULT');
INSERT INTO loans (loan_id, customer_id, loan_type, loan_amount, interest_rate, start_date, end_date, status) VALUES (28, 28, 'PERSONAL', 791959.88, 10.1, TO_DATE('10/26/2011', 'MM/DD/YYYY'), NULL, 'PAID');
INSERT INTO loans (loan_id, customer_id, loan_type, loan_amount, interest_rate, start_date, end_date, status) VALUES (29, 29, 'AUTO', 380994.75, 19.59, TO_DATE('7/6/2018', 'MM/DD/YYYY'), NULL, 'PAID');
INSERT INTO loans (loan_id, customer_id, loan_type, loan_amount, interest_rate, start_date, end_date, status) VALUES (30, 30, 'HOME', 873992.44, 13.84, TO_DATE('8/3/2017', 'MM/DD/YYYY'), NULL, 'APPROVED');
INSERT INTO loans (loan_id, customer_id, loan_type, loan_amount, interest_rate, start_date, end_date, status) VALUES (31, 31, 'PERSONAL', 117858.89, 15.71, TO_DATE('10/9/2009', 'MM/DD/YYYY'), NULL, 'PAID');
INSERT INTO loans (loan_id, customer_id, loan_type, loan_amount, interest_rate, start_date, end_date, status) VALUES (32, 32, 'AUTO', 403648.65, 1.2, TO_DATE('4/9/2001', 'MM/DD/YYYY'), NULL, 'PAID');
INSERT INTO loans (loan_id, customer_id, loan_type, loan_amount, interest_rate, start_date, end_date, status) VALUES (33, 33, 'AUTO', 269028.95, 4.27, TO_DATE('12/14/2006', 'MM/DD/YYYY'), NULL, 'DEFAULT');
INSERT INTO loans (loan_id, customer_id, loan_type, loan_amount, interest_rate, start_date, end_date, status) VALUES (34, 34, 'AUTO', 459582.77, 24.68, TO_DATE('11/23/2019', 'MM/DD/YYYY'), NULL, 'DEFAULT');
INSERT INTO loans (loan_id, customer_id, loan_type, loan_amount, interest_rate, start_date, end_date, status) VALUES (35, 35, 'HOME', 622796.26, 9.0, TO_DATE('10/6/2022', 'MM/DD/YYYY'), NULL, 'APPROVED');
INSERT INTO loans (loan_id, customer_id, loan_type, loan_amount, interest_rate, start_date, end_date, status) VALUES (36, 36, 'HOME', 222481.08, 20.78, TO_DATE('3/18/2010', 'MM/DD/YYYY'), NULL, 'PAID');
INSERT INTO loans (loan_id, customer_id, loan_type, loan_amount, interest_rate, start_date, end_date, status) VALUES (37, 37, 'HOME', 914317.2, 16.43, TO_DATE('6/1/2022', 'MM/DD/YYYY'), NULL, 'APPROVED');
INSERT INTO loans (loan_id, customer_id, loan_type, loan_amount, interest_rate, start_date, end_date, status) VALUES (38, 38, 'PERSONAL', 467783.66, 10.92, TO_DATE('9/5/2000', 'MM/DD/YYYY'), NULL, 'DEFAULT');
INSERT INTO loans (loan_id, customer_id, loan_type, loan_amount, interest_rate, start_date, end_date, status) VALUES (39, 39, 'PERSONAL', 330422.67, 2.28, TO_DATE('4/8/2006', 'MM/DD/YYYY'), NULL, 'APPROVED');
INSERT INTO loans (loan_id, customer_id, loan_type, loan_amount, interest_rate, start_date, end_date, status) VALUES (40, 40, 'HOME', 294471.08, 9.7, TO_DATE('1/6/2004', 'MM/DD/YYYY'), NULL, 'APPROVED');
INSERT INTO loans (loan_id, customer_id, loan_type, loan_amount, interest_rate, start_date, end_date, status) VALUES (41, 41, 'PERSONAL', 788474.23, 14.6, TO_DATE('8/21/2000', 'MM/DD/YYYY'), NULL, 'APPROVED');
INSERT INTO loans (loan_id, customer_id, loan_type, loan_amount, interest_rate, start_date, end_date, status) VALUES (42, 42, 'AUTO', 232919.56, 9.88, TO_DATE('12/18/2014', 'MM/DD/YYYY'), NULL, 'APPROVED');
INSERT INTO loans (loan_id, customer_id, loan_type, loan_amount, interest_rate, start_date, end_date, status) VALUES (43, 43, 'HOME', 724994.37, 23.06, TO_DATE('9/9/2003', 'MM/DD/YYYY'), NULL, 'PAID');
INSERT INTO loans (loan_id, customer_id, loan_type, loan_amount, interest_rate, start_date, end_date, status) VALUES (44, 44, 'PERSONAL', 471396.51, 17.92, TO_DATE('9/29/2022', 'MM/DD/YYYY'), NULL, 'APPROVED');
INSERT INTO loans (loan_id, customer_id, loan_type, loan_amount, interest_rate, start_date, end_date, status) VALUES (45, 45, 'AUTO', 168884.8, 20.2, TO_DATE('10/29/2006', 'MM/DD/YYYY'), NULL, 'PAID');
INSERT INTO loans (loan_id, customer_id, loan_type, loan_amount, interest_rate, start_date, end_date, status) VALUES (46, 46, 'PERSONAL', 475248.81, 4.69, TO_DATE('6/29/2005', 'MM/DD/YYYY'), NULL, 'APPROVED');
INSERT INTO loans (loan_id, customer_id, loan_type, loan_amount, interest_rate, start_date, end_date, status) VALUES (47, 47, 'AUTO', 825066.17, 12.47, TO_DATE('12/24/2020', 'MM/DD/YYYY'), NULL, 'PAID');
INSERT INTO loans (loan_id, customer_id, loan_type, loan_amount, interest_rate, start_date, end_date, status) VALUES (48, 48, 'PERSONAL', 747817.13, 12.49, TO_DATE('11/28/2020', 'MM/DD/YYYY'), NULL, 'DEFAULT');
INSERT INTO loans (loan_id, customer_id, loan_type, loan_amount, interest_rate, start_date, end_date, status) VALUES (49, 49, 'HOME', 109391.68, 8.45, TO_DATE('9/11/2009', 'MM/DD/YYYY'), NULL, 'APPROVED');
INSERT INTO loans (loan_id, customer_id, loan_type, loan_amount, interest_rate, start_date, end_date, status) VALUES (50, 50, 'HOME', 376627.58, 21.05, TO_DATE('12/17/2012', 'MM/DD/YYYY'), NULL, 'APPROVED');
INSERT INTO loans (loan_id, customer_id, loan_type, loan_amount, interest_rate, start_date, end_date, status) VALUES (51, 51, 'HOME', 350213.48, 11.56, TO_DATE('6/13/2016', 'MM/DD/YYYY'), NULL, 'APPROVED');
INSERT INTO loans (loan_id, customer_id, loan_type, loan_amount, interest_rate, start_date, end_date, status) VALUES (52, 52, 'PERSONAL', 320837.3, 14.33, TO_DATE('2/10/2018', 'MM/DD/YYYY'), NULL, 'PAID');
INSERT INTO loans (loan_id, customer_id, loan_type, loan_amount, interest_rate, start_date, end_date, status) VALUES (53, 53, 'AUTO', 787043.42, 8.68, TO_DATE('3/16/2013', 'MM/DD/YYYY'), NULL, 'APPROVED');
INSERT INTO loans (loan_id, customer_id, loan_type, loan_amount, interest_rate, start_date, end_date, status) VALUES (54, 54, 'HOME', 318716.71, 3.37, TO_DATE('8/4/2018', 'MM/DD/YYYY'), NULL, 'APPROVED');
INSERT INTO loans (loan_id, customer_id, loan_type, loan_amount, interest_rate, start_date, end_date, status) VALUES (55, 55, 'HOME', 490590.35, 23.7, TO_DATE('9/26/2012', 'MM/DD/YYYY'), NULL, 'APPROVED');
INSERT INTO loans (loan_id, customer_id, loan_type, loan_amount, interest_rate, start_date, end_date, status) VALUES (56, 56, 'PERSONAL', 292633.47, 8.05, TO_DATE('7/18/2005', 'MM/DD/YYYY'), NULL, 'APPROVED');
INSERT INTO loans (loan_id, customer_id, loan_type, loan_amount, interest_rate, start_date, end_date, status) VALUES (57, 57, 'PERSONAL', 775083.53, 15.1, TO_DATE('6/18/2005', 'MM/DD/YYYY'), NULL, 'DEFAULT');
INSERT INTO loans (loan_id, customer_id, loan_type, loan_amount, interest_rate, start_date, end_date, status) VALUES (58, 58, 'HOME', 862021.79, 5.42, TO_DATE('11/20/2018', 'MM/DD/YYYY'), NULL, 'DEFAULT');
INSERT INTO loans (loan_id, customer_id, loan_type, loan_amount, interest_rate, start_date, end_date, status) VALUES (59, 59, 'PERSONAL', 794077.21, 3.3, TO_DATE('9/12/2009', 'MM/DD/YYYY'), NULL, 'PAID');
INSERT INTO loans (loan_id, customer_id, loan_type, loan_amount, interest_rate, start_date, end_date, status) VALUES (60, 60, 'PERSONAL', 320753.79, 19.44, TO_DATE('2/2/2007', 'MM/DD/YYYY'), NULL, 'APPROVED');
INSERT INTO loans (loan_id, customer_id, loan_type, loan_amount, interest_rate, start_date, end_date, status) VALUES (61, 61, 'AUTO', 117291.35, 3.33, TO_DATE('9/9/2020', 'MM/DD/YYYY'), NULL, 'DEFAULT');
INSERT INTO loans (loan_id, customer_id, loan_type, loan_amount, interest_rate, start_date, end_date, status) VALUES (62, 62, 'HOME', 606328.98, 24.4, TO_DATE('7/29/2001', 'MM/DD/YYYY'), NULL, 'PAID');
INSERT INTO loans (loan_id, customer_id, loan_type, loan_amount, interest_rate, start_date, end_date, status) VALUES (63, 63, 'PERSONAL', 936454.68, 15.63, TO_DATE('4/29/2014', 'MM/DD/YYYY'), NULL, 'PAID');
INSERT INTO loans (loan_id, customer_id, loan_type, loan_amount, interest_rate, start_date, end_date, status) VALUES (64, 64, 'PERSONAL', 446030.6, 9.91, TO_DATE('6/18/2003', 'MM/DD/YYYY'), NULL, 'APPROVED');
INSERT INTO loans (loan_id, customer_id, loan_type, loan_amount, interest_rate, start_date, end_date, status) VALUES (65, 65, 'HOME', 357915.39, 24.33, TO_DATE('1/25/2017', 'MM/DD/YYYY'), NULL, 'PAID');
INSERT INTO loans (loan_id, customer_id, loan_type, loan_amount, interest_rate, start_date, end_date, status) VALUES (66, 66, 'PERSONAL', 882599.77, 3.93, TO_DATE('2/12/2016', 'MM/DD/YYYY'), NULL, 'PAID');
INSERT INTO loans (loan_id, customer_id, loan_type, loan_amount, interest_rate, start_date, end_date, status) VALUES (67, 67, 'HOME', 797030.64, 8.69, TO_DATE('9/25/2013', 'MM/DD/YYYY'), NULL, 'DEFAULT');
INSERT INTO loans (loan_id, customer_id, loan_type, loan_amount, interest_rate, start_date, end_date, status) VALUES (68, 68, 'AUTO', 935558.14, 11.09, TO_DATE('3/7/2003', 'MM/DD/YYYY'), NULL, 'APPROVED');
INSERT INTO loans (loan_id, customer_id, loan_type, loan_amount, interest_rate, start_date, end_date, status) VALUES (69, 69, 'AUTO', 948761.79, 7.46, TO_DATE('7/19/2010', 'MM/DD/YYYY'), NULL, 'DEFAULT');
INSERT INTO loans (loan_id, customer_id, loan_type, loan_amount, interest_rate, start_date, end_date, status) VALUES (70, 70, 'HOME', 319150.09, 6.87, TO_DATE('10/25/2007', 'MM/DD/YYYY'), NULL, 'PAID');
INSERT INTO loans (loan_id, customer_id, loan_type, loan_amount, interest_rate, start_date, end_date, status) VALUES (71, 71, 'AUTO', 394210.78, 0.98, TO_DATE('1/16/2001', 'MM/DD/YYYY'), NULL, 'DEFAULT');
INSERT INTO loans (loan_id, customer_id, loan_type, loan_amount, interest_rate, start_date, end_date, status) VALUES (72, 72, 'AUTO', 645955.05, 10.07, TO_DATE('1/28/2019', 'MM/DD/YYYY'), NULL, 'PAID');
INSERT INTO loans (loan_id, customer_id, loan_type, loan_amount, interest_rate, start_date, end_date, status) VALUES (73, 73, 'PERSONAL', 766270.29, 22.17, TO_DATE('9/5/2008', 'MM/DD/YYYY'), NULL, 'PAID');
INSERT INTO loans (loan_id, customer_id, loan_type, loan_amount, interest_rate, start_date, end_date, status) VALUES (74, 74, 'PERSONAL', 178829.89, 23.16, TO_DATE('9/15/2014', 'MM/DD/YYYY'), NULL, 'DEFAULT');
INSERT INTO loans (loan_id, customer_id, loan_type, loan_amount, interest_rate, start_date, end_date, status) VALUES (75, 75, 'AUTO', 998961.98, 6.31, TO_DATE('6/12/2013', 'MM/DD/YYYY'), NULL, 'APPROVED');